apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: movie-api
  name: movie-api
spec:
  containers:
  - image: "{{ .Values.image.movieApi.image }}:{{ .Values.image.movieApi.tag }}"
    name: movie-api
    imagePullPolicy: {{ .Values.image.movieApi.pullPolicy }}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
