apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: movie-view
  name: movie-view
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: movie-view
status:
  loadBalancer: {}
