apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: movie-api
  name: movie-api
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: movie-api
status:
  loadBalancer: {}
