replicaCount: 1

image:
  movieView:
    image: tkdduq8260/movie-view
    tag: "latest"
    pullPolicy: IfNotPresent
  movieApi:
    image: tkdduq8260/movie-api
    tag: "latest"
    pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
